### ISSUE TITLE
请问Mac使用会有影响吗

### ISSUE THREAD

**Issue by sv3nbeast** [kelvinBen/AppInfoScanner#1]
因为在目录发现了exe，请问这个是会被调用的吗
![image](https://user-images.githubusercontent.com/55974091/102299835-a6b94e00-3f8e-11eb-8205-28948f5b939f.png)

感谢师傅分享的工具

**Comment by kelvinBen** [comment]
strings工具用于提取ELF文件中的字符串，在Windows下对ELF文件、IPA文件进行操作的时候会进行调用，在MAC下会调用系统自有的strings命令。
