### ISSUE TITLE
WEB扫描文件夹的功能还没实现呀

### ISSUE THREAD

**Issue by go1f** [kelvinBen/AppInfoScanner#10]
开头以为有bug
import hashlib
40行，变量写错了，dir_file_path
42行附近，要改一下，不然报nonetype的错。
    md5 = hashlib.md5()
    md5.update(f.read())
    dex_md5 = str(md5.hexdigest()).upper()

![图片](https://user-images.githubusercontent.com/54230694/126599261-9afb0cdd-2100-45d3-97b4-6aaa8f4b69b6.png)

改了几行，再写下去发现有些属性还没实现，还没写好哈哈哈，加油
![图片](https://user-images.githubusercontent.com/54230694/126599680-e23ae308-8196-42a2-9176-205b0f75dc97.png)

**Comment by kelvinBen** [comment]
@go1f 感谢反馈！问题已修复，请下载最新版本
