### ISSUE TITLE
运行报错，没有Bootstrapper模块文件。

### ISSUE THREAD

**Issue by cascklhljhn** [kelvinBen/AppInfoScanner#13]
ImportError: cannot import name 'Bootstrapper' from 'libs.core' (unknown location)

**Comment by BypassKing** [comment]
老哥，我也遇到这个问题了。是哪里环境的问题 ？？？

**Comment by kelvinBen** [comment]
正常情况下：libc/core下有个__init__.py文件，如果下载的代码中没有这个文件就会出现（ImportError: cannot import name 'Bootstrapper' from 'libs.core' (unknown location)）这个错误，可以尝试重新拉一下代码或者访问访问下面的链接，下载__init__.py文件并放在libc/core目录下，即可解决

https://github.com/kelvinBen/AppInfoScanner/blob/master/libs/core/__init__.py
