### ISSUE TITLE
星链计划

### ISSUE THREAD

**Issue by LoRexxar** [kelvinBen/AppInfoScanner#3]
您好，

我是星链计划的负责人，觉得您的项目很不错，想要将AppInfoScanner收录到星链计划中。

关于星链计划2.0的任何信息，可以了解

https://github.com/knownsec/404StarLink2.0-Galaxy

如果您对我的提议感兴趣，麻烦通过上述链接中的微信联系我，感谢。

**Comment by kelvinBen** [comment]
已添加好友并反馈
